# Generated by Django 2.0.3 on 2018-04-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180406_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='order', to='shop.User'),
        ),
    ]
